-- ********** Data Definition Language - Schema 'CRM' - Database 'usta_empresarial' ********** --

CREATE SCHEMA CRM;

-- Table 'TIPO_MEDIO' | Schema 'CRM'

CREATE TABLE CRM.TIPO_MEDIO(

    CODIGO SERIAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    VALOR_PROM INT NOT NULL,
    ESTADO BOOLEAN NOT NULL,

    CONSTRAINT TIPO_MEDIO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX TIPO_MEDIO_UINDEX
    ON CRM.TIPO_MEDIO (CODIGO);

COMMENT ON TABLE CRM.TIPO_MEDIO IS 'Tabla que describe los TIPOs de MEDIO disponibles para ser consumidos.';
COMMENT ON COLUMN CRM.TIPO_MEDIO.CODIGO IS 'Código del TIPO de MEDIO de divulgación (escrito, radio, tv, internet)';
COMMENT ON COLUMN CRM.TIPO_MEDIO.NOMBRE IS 'NOMBRE del MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.DESCRIPCION IS 'Descripción del MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.VALOR_PROM IS 'VALOR PROMEDIO del MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.ESTADO IS 'Activo (1), Inactivo (0)';

-- Table 'PERIODO' | Schema 'CRM'

CREATE TABLE CRM.PERIODO(

    CODIGO SERIAL NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ESTADO BOOLEAN NOT NULL,

    CONSTRAINT PERIODO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX PERIODO_UINDEX
    ON CRM.PERIODO (CODIGO);

COMMENT ON TABLE CRM.PERIODO IS 'Tabla que describe el PERIODO de publicidad de la campaña.';
COMMENT ON COLUMN CRM.PERIODO.CODIGO IS 'Código del PERIODO de publicidad.';
COMMENT ON COLUMN CRM.PERIODO.FECHA_INICIO IS 'FECHA inicio.';
COMMENT ON COLUMN CRM.PERIODO.FECHA_FIN IS 'FECHA final.';
COMMENT ON COLUMN CRM.PERIODO.ESTADO IS 'Activo (1), Inactivo (0)';

-- Table 'CAMPANIA' | Schema 'CRM'

CREATE TABLE CRM.CAMPANIA(

    CODIGO SERIAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PERIODO_COD INT NOT NULL,
    VALOR DECIMAL NOT NULL,
    ESTADO BOOLEAN NOT NULL,

    CONSTRAINT CAMPANIA_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT CAMPANIA_PERIODO_FK
        FOREIGN KEY (PERIODO_COD) REFERENCES CRM.PERIODO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE UNIQUE INDEX CAMPANIA_UINDEX
    ON CRM.CAMPANIA (CODIGO);

COMMENT ON TABLE CRM.CAMPANIA IS 'Tabla que describe las campañas de la compañía.';
COMMENT ON COLUMN CRM.CAMPANIA.CODIGO IS 'Código de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.NOMBRE IS 'NOMBRE de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.DESCRIPCION IS 'Descripción de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.FECHA_INICIO IS 'FECHA de Inicio de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.FECHA_FIN IS 'FECHA de Finalización de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.PERIODO_COD IS 'Código del PERIODO asignado a la campaña';
COMMENT ON COLUMN CRM.CAMPANIA.VALOR IS 'Precio PROMEDIO de la campaña publicitaria';
COMMENT ON COLUMN CRM.CAMPANIA.ESTADO IS 'Activo (1), Inactivo (0)';

-- Table 'EVENTO' | Schema 'CRM'

CREATE TABLE CRM.EVENTO(

    CODIGO SERIAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    FECHA DATE NOT NULL,
    CAMPANIA_COD INT NOT NULL,
    ESTADO BOOLEAN NOT NULL,

    CONSTRAINT EVENTO_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT EVENTO_CAMPANIA_FK
        FOREIGN KEY (CAMPANIA_COD) REFERENCES CRM.CAMPANIA (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE UNIQUE INDEX EVENTO_UINDEX
    ON CRM.EVENTO (CODIGO);

COMMENT ON TABLE CRM.EVENTO IS 'Tabla que describe los EVENTOs de la compañía.';
COMMENT ON COLUMN CRM.EVENTO.CODIGO IS 'Código del EVENTO';
COMMENT ON COLUMN CRM.EVENTO.NOMBRE IS 'NOMBRE del EVENTO';
COMMENT ON COLUMN CRM.EVENTO.DESCRIPCION IS 'Descripción del EVENTO';
COMMENT ON COLUMN CRM.EVENTO.FECHA IS 'FECHA del EVENTO';
COMMENT ON COLUMN CRM.EVENTO.CAMPANIA_COD IS 'Código de la campaña asignada al EVENTO';
COMMENT ON COLUMN CRM.EVENTO.ESTADO IS 'Activo (1), Inactivo (0)';

-- Table 'RECURSO' | Schema 'CRM'

CREATE TABLE CRM.RECURSO(

    CODIGO SERIAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO INT NOT NULL,
    DESCRIPCION VARCHAR(200),
    VALOR DECIMAL NOT NULL,

    CONSTRAINT RECURSO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX RECURSO_UINDEX
    ON CRM.RECURSO (CODIGO);

COMMENT ON TABLE CRM.RECURSO IS 'Tabla que describe los RECURSOs con los que cuenta la compañía.';
COMMENT ON COLUMN CRM.RECURSO.CODIGO IS 'Código del RECURSO';
COMMENT ON COLUMN CRM.RECURSO.NOMBRE IS 'NOMBRE del RECURSO';
COMMENT ON COLUMN CRM.RECURSO.DESCRIPCION IS 'Descripción del RECURSO';
COMMENT ON COLUMN CRM.RECURSO.TIPO IS 'TIPO del RECURSO';
COMMENT ON COLUMN CRM.RECURSO.VALOR IS 'Costo PROMEDIO del RECURSO';

-- Table 'MEDIO' | Schema 'CRM'

CREATE TABLE CRM.MEDIO(

    CODIGO SERIAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    TIPO_MEDIO_COD INT NOT NULL,
    EVENTO_COD INT NOT NULL,
    RECURSO_COD INT NOT NULL,
    VALOR DECIMAL NOT NULL,
    ESTADO BOOLEAN NOT NULL,

    CONSTRAINT MEDIO_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT MEDIO_TIPO_MEDIO_FK
        FOREIGN KEY (TIPO_MEDIO_COD) REFERENCES CRM.TIPO_MEDIO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT MEDIO_EVENTO_FK
        FOREIGN KEY (EVENTO_COD) REFERENCES CRM.EVENTO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT MEDIO_RECURSO_FK
       FOREIGN KEY (RECURSO_COD) REFERENCES CRM.RECURSO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

COMMENT ON TABLE CRM.MEDIO IS 'Tabla que describe los MEDIOs publicitarios disponibles para ser consumidos.';
COMMENT ON COLUMN CRM.MEDIO.CODIGO IS 'Código del RECURSO';
COMMENT ON COLUMN CRM.MEDIO.NOMBRE IS 'NOMBRE del RECURSO';
COMMENT ON COLUMN CRM.MEDIO.DESCRIPCION IS 'Descripción del MEDIO';
COMMENT ON COLUMN CRM.MEDIO.TIPO_MEDIO_COD IS 'Código correspondiente al TIPO del MEDIO a consumir';
COMMENT ON COLUMN CRM.MEDIO.EVENTO_COD IS 'Código correspondiente al EVENTO del MEDIO a consumir';
COMMENT ON COLUMN CRM.MEDIO.RECURSO_COD IS 'Código correspondiente al recuso del MEDIO a consumir';
COMMENT ON COLUMN CRM.MEDIO.VALOR IS 'Costo PROMEDIO del MEDIO a consumir';
COMMENT ON COLUMN CRM.MEDIO.ESTADO IS 'Activo (1), Inactivo (0)';

CREATE UNIQUE INDEX MEDIO_UINDEX
    ON CRM.MEDIO (CODIGO);