INSERT INTO ustanomina.HOJA_VIDA(DOCUMENTO, NOMBRE, APELLIDO,NACIMIENTO_FECHA,NACIMIENTO_LUGAR,DIRECCION,TELEFONO) values(10208,'Laura','Castillo Cortes','1956-02-16','Tunja','cra9#24-71',30172);

INSERT INTO ustanomina.CARGO(CODIGO,NOMBRE,FUNCION,COMPETENCIAS) VALUES(1020,'Presidente','Administrar toda la empresa','Altruista y honesto');

INSERT INTO ustanomina.DEPENDENCIA(CODIGO,NOMBRE,DEPENDENCIA_PADRE,ESTADO) VALUES(1021,'Nomina',null,true);

INSERT INTO ustanomina.DEPENDENCIA(CODIGO,NOMBRE,DEPENDENCIA_PADRE,ESTADO) VALUES(1022,'Finanzas',1021,true);


INSERT INTO ustanomina.CONTRATO(CODIGO,FECHA_INiCIO,FECHA_FIN,SALARIO,HOJA_VIDA_DOC,DEPENDENCIA_COD,CARGO_COD) VALUES(1,'2019-02-16','2020-02-16',1000000,10208,1022,1020);
INSERT INTO ustanomina.PERIODO(CODIGO,FECHA_INICIO,FECHA_FIN,ESTADO) VALUES(1,'2019-01-01','2019-06-01',true);
INSERT INTO ustanomina.CONCEPTO(
	CODIGO, NOMBRE, DESCRIPCION, TIPO, FORMULA, ESTADO)
	VALUES (1, 'SALARIO','SALARIO', false, 'SALARIO/30*DIAS TRABAJADOS', true);
INSERT INTO ustanomina.NOMINA(CONTRATO_COD, CONCEPTO_COD, PERIODO_COD, VALOR, USUARIO_INSERT, FECHA_INSERT, USUARIO_UPDATE, FECHA_UPDATE)
	VALUES (1, 1, 1, 100000, 'LAURA','2019-02-12','LAURA', '2019-04-12');